version: '3'

services:
    test_php:
      build: docker/php
      image: test_php
      expose:
          - 9000
      volumes:
          - .:/var/www/html
          - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      entrypoint: docker-php-entrypoint php-fpm
      restart: always
      container_name: test_php

    test_nginx:
        image: nginx:alpine
        ports:
            - '80:80'
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/log/:/var/log/nginx/
            - .:/var/www/html
        restart: always
        container_name: test_nginx

    test_mysql:
      image: mysql:5.7
      container_name: ${DB_HOST}
      restart: unless-stopped
      ports:
        - '3306:3306'
      environment:
        - MYSQL_DATABASE=${DB_NAME}
        - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        - MYSQL_USER=${DB_USERNAME}
        - MYSQL_PASSWORD=${DB_PASSWORD}
      command: '--default-authentication-plugin=mysql_native_password'