version: '3'

services:
    test_php:
      build: docker/php
      image: test_php
      expose:
          - 9000
      volumes:
          - .:/var/www/html
          - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      entrypoint: docker-php-entrypoint php-fpm
      restart: always
      container_name: test_php